### ISSUE TITLE
Support tracks

### ISSUE THREAD

**Issue by heff** [muxinc/custom-video-element#3]
Re: muxinc/hls-video-element#6

Need to support child text track elements as part of this approach.

I attempted to just use a slot inside the `<video>` and let track elements pass through naturally, but that doesn't work. Tracks need to be direct children of the native `<video>`, and slot children apparently don't count.

I think the best approach now is going to be a child tree mutation observer that copies track elements from the body of the custom element to the body of the video element. And then watch for updates and mimic them. Not the most exciting approach but should work for 99% of the use cases of tracks, if not all.

**Comment by luwes** [comment]
Fixed in #4
